#!/usr/bin/env bash

set -eou pipefail

# check_password - Check a pass entry against pwnedpasswords.com.
#
# Takes in a pass entry (example: Email/zx2c4.com) and outputs the entries
# tested and any compromises to stderr.
function check_password() {
	password=${1}
	verbose_log "Checking entry ${password}"

	sha1=$(echo -n "${password}" | openssl dgst -sha1 -binary | xxd -p)
	short=${sha1:0:5}

	echo "${sha1} | ${entry}"
	resp=$(curl -s -X GET https://api.pwnedpasswords.com/range/${short})

	# Compare local hash against the ones we got from pwnedpasswords.com.
	for h in $resp; do
		cleaned_hash=$(echo "${short}${h}" | awk -F: '{ print $1 }')

		if [[ "${cleaned_hash}" == ${sha1} ]]; then
			(>&2 echo -e "\e[31m!!\e[33m Your password for ${entry} with SHA1 ${sha1} has been compromised!\e[0m")
		fi
	done
}

# Main program.
#
# Run through all .gpg files in password store.
function main() {
	# Set IFS to be able to cope with spaces in file names.
	IFS=$'\n'

	for pass_entry in $(pass git ls-files *.gpg); do

		# Support characters with åäö etc..
		escaped_entry="$(printf %b ${pass_entry})"
		entry=${escaped_entry%\"}
		entry=${entry#\"}
		entry=${entry%.gpg}
		verbose_log "Checking password file ${entry}"

		# Check the pass entries:
		if [ "$FULL_FILE" = true ] ; then
			while read p; do
				check_password "${p}"
			done <<< "$(pass -- "${entry}")"
		else
			check_password "$(pass -- "${entry}" | head -n 1)"
		fi
	done
}

# Verbose logging:
function verbose_log() {
	if [ "$VERBOSE" = true ] ; then 
		echo "VERBOSE: ${1}"
	fi
}

# Help:
function usage() { 
	echo "Usage: $0 [-h] [-v] [-f]" 1>&2; 
	exit 1; 
}

# Parse input:
OPTS=`getopt hvf $*`
if [ $? != 0 ] ; then 
	echo "Failed parsing options." >&2 
	usage
	exit 1
fi

eval set -- "$OPTS"

VERBOSE=false
FULL_FILE=false

while true; do
	case "$1" in
		-v )    VERBOSE=true; shift ;;
		-h )    usage; shift ;;
		-f )    FULL_FILE=true; shift ;;
		-- )    shift; break ;;
		* )     usage; break ;;
	esac
done

# Run the program.
main
